# Generated by Django 5.2 on 2025-06-14 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=511, unique=True)),
                ('measure', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(default=2025)),
                ('value', models.FloatField(default=0.0)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='gross_regional_product.parameters')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='gross_regional_product.regions')),
            ],
            options={
                'unique_together': {('root', 'parameter', 'date')},
            },
        ),
    ]
