# Generated by Django 5.2 on 2025-06-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gross_regional_product', '0002_alter_parameters_id_alter_regions_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='root',
            new_name='region',
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('region', 'parameter', 'date')},
        ),
    ]
