# Generated by Django 5.2 on 2025-06-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gross_regional_product', '0003_rename_root_data_region_alter_data_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='date',
            new_name='year',
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('region', 'parameter', 'year')},
        ),
    ]
